database:
  path: "./test-database.sqlite"
frontend: "./frontend"
log-file: "general.log"
server-settings:
  port: ":8080"
  idle-timeout: 120s
  read-timeout: 1s
  write-timeout: 1s
swagger-spec: "./docs/swagger.yaml"
