database-settings:
  name: "training-notebook-test-db"
  uri: "mongodb://localhost:27017"
server-settings:
  host: "http://localhost"
  port: ":5000"
  idle-timeout: 120s
  read-timeout: 1s
  write-timeout: 1s
  api:
    prefix: "/api/v1"
